import {
  natours,
  admin,
  ecommerce,
  education,
  real_estate,
  social_clone,
  chefmei,
  foodapp,
  gpt3,
  hoobank,
  munch,
  contact,
  mediaApp,
  carRentals,
} from "../assets";

export const data = [
  {
    id: 1,
    image: carRentals,
    title: "Basic webpage utilizing Next.js and Typescript",
    github: "https://github.com/olaoyetijani/car_rentals",
    demo: "https://car-rentals-seven.vercel.app/",
  },
  {
    id: 2,
    image: mediaApp,
    title: "Online Platform for memories: MERN",
    github: "https://github.com/olaoyetijani/media-backend",
    demo: "https://media-frontend-drab.vercel.app/",
  },
  {
    id: 3,
    image: natours,
    title: "Travel && Tour App: MERN",
    github: "https://github.com/olaoyetijani/natours",
    demo: "https://natours-dev-z1mi.onrender.com/",
  },
  {
    id: 4,
    image: real_estate,
    title: "Real Estate App: Next.js + bayut API",
    github: "https://github.com/olaoyetijani/realestateapp",
    demo: "https://realestateapp-delta.vercel.app/",
  },
  {
    id: 5,
    image: munch,
    title: "Blog App: Next.js + graphQL + CMS",
    github: "https://github.com/olaoyetijani/techmunch",
    demo: "https://techmunch.vercel.app/",
  },
  {
    id: 6,
    image: ecommerce,
    title: "E-commerce App: Next.js + Stripe.js",
    github: "https://github.com/olaoyetijani/e-commerceApp",
    demo: "https://e-commerce-app-nu.vercel.app/",
  },
  {
    id: 7,
    image: admin,
    title: "Admin Dashboard: React.js",
    github: "https://github.com/olaoyetijani/AdminDashboard",
    demo: "https://admin-dashboard-puce.vercel.app/",
  },
  {
    id: 8,
    image: contact,
    title: "Add Contact: React.js + Redux",
    github: "https://github.com/olaoyetijani/addcontact__redux",
    demo: "https://addcontact.vercel.app/",
  },
  {
    id: 9,
    image: chefmei,
    title: "Restaurant App: React.js",
    github: "https://github.com/olaoyetijani/chefmei",
    demo: "https://chefmei.vercel.app/",
  },
  {
    id: 10,
    image: foodapp,
    title: "Food website: React.js + TailWind CSS",
    github: "https://github.com/olaoyetijani/foodie",
    demo: "https://foodie-indol.vercel.app/",
  },
  {
    id: 11,
    image: gpt3,
    title: "GPT-3: React.js",
    github: "https://github.com/olaoyetijani/gpt3",
    demo: "https://gpt3-9dx12bh4p-olaoyetijani.vercel.app/",
  },
  {
    id: 12,
    image: hoobank,
    title: "Bank Website: React.js + TailWind CSS ",
    github: "https://github.com/olaoyetijani/Hoobank",
    demo: "https://hoobank-clone-tau.vercel.app/",
  },

  {
    id: 13,
    image: education,
    title: "Education Website: HTML + CSS + JS",
    github: "https://github.com/olaoyetijani/educationwebsite",
    demo: "https://educationwebsite.vercel.app/",
  },
  {
    id: 14,
    image: social_clone,
    title: "Meet Social: HTML + CSS + JS",
    github: "https://github.com/olaoyetijani/meetsocialapp",
    demo: "https://meetsocialapp.vercel.app/",
  },
];
