import {
  natours,
  admin,
  ecommerce,
  education,
  real_estate,
  social_clone,
  chefmei,
  foodapp,
  gpt3,
  hoobank,
  munch,
  contact,
  mediaApp,
  carRentals,
  WildOasis,
  FastPizza,
  Hotelportal,
  Tenancy,
  NSE,
  Javascript,
  Node,
  ReactCourse,
  AwardFirst,
  AwardSec,
  Database,
} from "../assets";
import {
  All,
  CubeCover,
  FTTH,
  Kwik,
  MrWins,
  TaxPayment,
  TixAfrica,
  TravelWIngs,
  Trips,
} from "../assets/videos";

export const certifications = [
  // {
  //   id: 0,
  //   image: NSE,
  //   title: "GMNSE, CPE",
  //   issuer: "The Nigeria Society of Engineers",
  // },
  {
    id: 0,
    image: Javascript,
    title: "JavaScript Algorithms and Data Structures MasterClass",
    issuer: "Udemy",
  },
  {
    id: 1,
    image: Node,
    title: "Node.js, Express.js, MongoDB & More: The Complete BootCamp.",
    issuer: "Udemy",
  },

  {
    id: 2,
    image: Database,
    title: "Data Modelling & Relational Data Architecture",
    issuer: "Udemy",
  },
  {
    id: 3,
    image: ReactCourse,
    title: "The Ultimate React Course, React, Redux & More",
    issuer: "Udemy",
  },
  {
    id: 4,
    image: NSE,
    title: "B.Tech, Gmnse, Computer Engineering",
    issuer: "NSE",
  },
  {
    id: 5,
    image: AwardFirst,
    title: "Customer Service Award",
    issuer: "Project Director",
  },
  {
    id: 6,
    image: AwardSec,
    title: "Customer Service Award",
    issuer: "Project Director",
  },
];

export const videoData = [
  {
    id: 0,
    video: FTTH,
    title: "MTN FibreX / MyMTN App",
  },
  {
    id: 1,
    video: TixAfrica,
    title: "Tix Africa / MoMo PSB App",
  },
  {
    id: 2,
    video: MrWins,
    title: "MrWins Lotto / MoMo PSB App",
  },
  {
    id: 3,
    video: Trips,
    title: "Trips / MoMo PSB App",
  },
  {
    id: 4,
    video: CubeCover,
    title: "CubeCover(Health Insurance) / MoMo PSB App",
  },
  {
    id: 5,
    video: TaxPayment,
    title: "Tax Payment / MoMo PSB App",
  },
  {
    id: 6,
    video: TravelWIngs,
    title: "Travel Wings / MoMo PSB App",
  },
  {
    id: 7,
    video: Kwik,
    title: "Kwik(Logistics) / MoMo PSB App",
  },
  {
    id: 8,
    video: All,
    title: "All Apps / MoMo PSB App",
  },
];

export const data = [
  {
    id: 0,
    image: Tenancy,
    title: "MTN Tenancy Dashboard",
    github: "",
    demo: "https://pub-za.appcubecloud.com/magno/render/0000000001Dp0kC1yB6n/appdev__MtnTenancy/Login",
  },
  {
    id: 1,
    image: WildOasis,
    title: "Hotel Reservations & Booking",
    github: "https://github.com/olaoyetijani/wordwise",
    demo: "https://reservationmanagement.vercel.app/",
  },
  {
    id: 2,
    image: FastPizza,
    title: "QuickBite",
    github: "https://github.com/olaoyetijani/fastPizza",
    demo: "https://fast-pizza-virid-five.vercel.app/",
  },
  {
    id: 3,
    image: Hotelportal,
    title: "Integrated Hotel Management(Admin Portal)",
    github: "https://github.com/olaoyetijani/hotelportal",
    demo: "https://cabinsbooking.netlify.app/account",
  },
  {
    id: 4,
    image: carRentals,
    title: "Basic webpage utilizing Next.js and Typescript",
    github: "https://github.com/olaoyetijani/car_rentals",
    demo: "https://car-rentals-seven.vercel.app/",
  },
  {
    id: 5,
    image: mediaApp,
    title: "Online Platform for memories: MERN",
    github: "https://github.com/olaoyetijani/media-backend",
    demo: "https://media-frontend-drab.vercel.app/",
  },
  {
    id: 6,
    image: natours,
    title: "Travel && Tour App: MERN",
    github: "https://github.com/olaoyetijani/natours",
    demo: "https://natours-dev-z1mi.onrender.com/",
  },
  {
    id: 7,
    image: real_estate,
    title: "Real Estate App: Next.js + bayut API",
    github: "https://github.com/olaoyetijani/realestateapp",
    demo: "https://realestateapp-delta.vercel.app/",
  },
  {
    id: 8,
    image: munch,
    title: "Blog App: Next.js + graphQL + CMS",
    github: "https://github.com/olaoyetijani/techmunch",
    demo: "https://techmunch.vercel.app/",
  },
  {
    id: 9,
    image: ecommerce,
    title: "E-commerce App: Next.js + Stripe.js",
    github: "https://github.com/olaoyetijani/e-commerceApp",
    demo: "https://e-commerce-app-nu.vercel.app/",
  },
  {
    id: 10,
    image: admin,
    title: "Admin Dashboard: React.js",
    github: "https://github.com/olaoyetijani/AdminDashboard",
    demo: "https://admin-dashboard-puce.vercel.app/",
  },
  {
    id: 11,
    image: contact,
    title: "Add Contact: React.js + Redux",
    github: "https://github.com/olaoyetijani/addcontact__redux",
    demo: "https://addcontact.vercel.app/",
  },
  {
    id: 12,
    image: chefmei,
    title: "Restaurant App: React.js",
    github: "https://github.com/olaoyetijani/chefmei",
    demo: "https://chefmei.vercel.app/",
  },
  {
    id: 13,
    image: foodapp,
    title: "Food website: React.js + TailWind CSS",
    github: "https://github.com/olaoyetijani/foodie",
    demo: "https://foodie-indol.vercel.app/",
  },
  {
    id: 14,
    image: gpt3,
    title: "GPT-3: React.js",
    github: "https://github.com/olaoyetijani/gpt3",
    demo: "https://gpt3-9dx12bh4p-olaoyetijani.vercel.app/",
  },
  {
    id: 15,
    image: hoobank,
    title: "Bank Website: React.js + TailWind CSS ",
    github: "https://github.com/olaoyetijani/Hoobank",
    demo: "https://hoobank-clone-tau.vercel.app/",
  },

  {
    id: 16,
    image: education,
    title: "Education Website: HTML + CSS + JS",
    github: "https://github.com/olaoyetijani/educationwebsite",
    demo: "https://educationwebsite.vercel.app/",
  },
  {
    id: 17,
    image: social_clone,
    title: "Meet Social: HTML + CSS + JS",
    github: "https://github.com/olaoyetijani/meetsocialapp",
    demo: "https://meetsocialapp.vercel.app/",
  },
];
